### ISSUE TITLE
Add autoformatting and linting configuration

### ISSUE THREAD

**Issue by mbarlow12** [RMI/OPGEEv4#15]
The codebase would benefit from leveraging modern Python linting and autoformatting. While there are several tools available, I propose we use [`ruff`](https://docs.astral.sh/ruff/) for its speed, compatibility with exiting tools/rules, and the team behind it is also the maintainer of `uv`.

This enhancement would
* quickly raise formatting/style issues
* help catch some common bugs and known risky code patterns
* add consistent format and code style to all `.py` files
* integrate with developer tools to perform formatting on save or as a pre-commit hook

Below is a draft for a sensible configuration. It could be added in a `ruff.toml` file in the repo root, or we can add this to the existing `pyproject.toml` if we prefix all tables with `tool.ruff.`.
```toml
# Ruff configuration file - extending defaults

# Change line length from default 88 to 120
line-length = 120

extend-exclude = ["build", "dist", "sdist", "__pycache__", "**/*.pyi"]

[lint]
# Extend the default rules (E4, E7, E9, F) with additional rules
extend-select = [
  "D",   # pydocstyle
  "DOC", # pydoclint
  "I",   # isort
  "N",   # pep8-naming
  "B",   # flake8-bugbear
  "C4",  # flake8-comprehensions
  "UP",  # pyupgrade
  "W",   # pycodestyle warnings
  "RUF", # Ruff-specific rules
  "BLE", # blind-except
  "COM", # flake8-commas (trailing commas)
  "DTZ", # flake8-datetimez (aware datetime)
  "ERA", # eradicate (commented out code)
  "PTH", # use pathlib
  "Q",   # flake8-quotes
  "RET", # flake8-return (consistent returns)
  "SIM", # flake8-simplify
  "TD",  # flake8-todos
  "TRY", # flake8-try-except-raise
  "TID", # flake8-tidy-imports

  # Performance rules
  "PLC",
  "PLE",
  "PLR",
  "PLW",  # pylint checks
  "C",    # flake8-comprehensions
  "PERF", # perflint

  # Type checking rules
  "ANN",
  "TC",
  "PYI",
  "PT",
  "PGH",
  "ARG",

  # Complexity
  "C901",

  # Print statements
  "T20",
]

# to avoid conflicts with the ruff formatter (see https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules)
ignore = [
  "W191",
  "E111",
  "E114",
  "E117",
  "D206",
  "D300",
  "COM812",
  "COM819",
  "Q000",
  "Q001",
  "Q002",
  "Q003",
]

preview = true

# Task tags configuration
task-tags = ["TODO", "FIXME"]

# Per-file rule ignores
[lint.per-file-ignores]
# Allow unused imports in __init__.py files
"__init__.py" = ["F401"]
# Allow unused arguments in tests
"test_*.py" = ["ARG001"]

# isort configuration
[lint.isort]
known-first-party = ["opgee"] # Adjust with your project name

# Ban relative imports
[lint.flake8-tidy-imports]
ban-relative-imports = "all"

# Configure quotes style (only needed if different from defaults)
[lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "double"
multiline-quotes = "double"

# Configure rule-specific settings
[lint.mccabe]
# Maximum cyclomatic complexity allowed per function
max-complexity = 12

# Configure complexity and line count
# [lint.flake8-bugbear]

[lint.pycodestyle]
max-line-length = 144

# Configure docstring style for reStructuredText
[lint.pydocstyle]
convention = "numpy" # This is closest to reStructuredText in ruff
# check-docstring-types = true # Check type consistency between docstrings and annotations

# Cognitive complexity settings
# [lint.cognitive-complexity]
# max-cognitive-complexity = 12

# Function length settings
[lint.pylint]
max-statements = 75   # Maximum number of statements in a function
max-nested-blocks = 5 # Maximum number of nested blocks
max-args = 10

# Extra customization for naming conventions
[lint.pep8-naming]
extend-ignore-names = ["setUp", "tearDown", "setUpClass", "tearDownClass"]

# Type checking configurations
[lint.flake8-annotations]
mypy-init-return = true # Check for proper __init__ return type annotations

# Type checking import configurations
[lint.flake8-type-checking]
strict = true # Enforce strict type checking imports

[format]
docstring-code-format = true
preview = true
```
